### ISSUE TITLE
Accessing ollama without API?

### ISSUE THREAD

**Issue by abdessalaam** [mitja/llamatunnel#1]
Thank you for this very useful project, and a clear tutorial. It works great when I use OpenWebUI.
However, since I already have api.domain.xyz pointing to my local ollama, I wanted to utilize it in some other services, like [paperless-gpt](https://github.com/icereed/paperless-gpt). That service assumes there is no api needed for ollama so when connecting to my api.domain.xyz I get an error.

How to bypass that? Thanks!

**Comment by mitja** [comment]
If the other app is on your local network, and you can accept the reduced security, you could allow access without authentication from a certain IP address or IP range. This would include an IP address/range that your other service is calling Ollama from. 

Would that meet your requirements/use case? If yes, I would create a patch to add this feature. In the meantime, ...

Here is an example caddy config that implements this: 

```
*.{$DOMAIN_NAME}:443 {
	tls {
		dns cloudflare {$CLOUDFLARE_API_TOKEN}
		resolvers 1.1.1.1
	}
	@apiValidApiKey {
		host {$API_SUBDOMAIN}.{$DOMAIN_NAME}
		header Authorization "Bearer {$OLLAMA_API_KEY}"
	}
	@allowedIPs {
		remote_ip {$ALLOWED_IP_RANGE}
                # enter directly here, or keep it as a variable and update docker-compose.yml and .env accordingly
		# Example: 192.168.1.0/24 for a subnet or 10.0.0.1 for a single IP
		# You can also use multiple IPs/ranges separated by spaces:
		# remote_ip 192.168.1.0/24 10.0.0.1 172.16.0.0/16
                # You can also use a single IP like so: 192.168.1.2/:32
	}
	@api {
		host {$API_SUBDOMAIN}.{$DOMAIN_NAME}
	}
	
	# Handle API requests
	handle @api {
		# Create a matcher for requests that have EITHER valid API key OR allowed IP
		@validKeyOrAllowedIP {
			or {
				matcher @apiValidApiKey
				matcher @allowedIPs
			}
		}
		
		# If the request has either valid key or allowed IP, proxy to Ollama
		handle @validKeyOrAllowedIP {
			reverse_proxy {$OLLAMA_URL}
		}
		
		# If neither valid key nor allowed IP, return 401
		header Content-Type application/json
		root * /srv
		rewrite * /401.json
		file_server
	}
	
	# Handle web UI requests
	@app host {$APP_SUBDOMAIN}.{$DOMAIN_NAME}
	reverse_proxy @app {$WEBUI_SERVICE_NAME}:8080
	log
}
```

Change your Caddy file, then, add that the `$ALLOWED_IP_RANGE` variable to your `docker-compose.yml`, and your `.env` files:

docker-compose.yml:

```yaml
   # ... the other parts remain the same...
  #--- Caddy ---
  {{caddy_service_name}}:
    build:
      context: ./images/caddy
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - {{webui_service_name}}
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - API_SUBDOMAIN=${API_SUBDOMAIN}
      - APP_SUBDOMAIN=${APP_SUBDOMAIN}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - WEBUI_SERVICE_NAME=${WEBUI_SERVICE_NAME} 
      - ALLOWED_IP_RANGE=${ALLOWED_IP_RANGE} # <<<< add this line
    volumes:
    ... rest remains the same
```

.env:

```
ALLOWED_IP_RANGE="192.168.1.0/24"
```
